/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppCheckoutRouteImport } from './routes/_app/checkout'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppRestaurantRestaurantIdRouteImport } from './routes/_app/restaurant.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/_app/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/_app/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/_app/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/_app/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestaurantRestaurantIdRoute =
  AppRestaurantRestaurantIdRouteImport.update({
    id: '/_app/restaurant/$restaurantId',
    path: '/restaurant/$restaurantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/restaurant/$restaurantId': typeof AppRestaurantRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/restaurant/$restaurantId': typeof AppRestaurantRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/restaurant/$restaurantId': typeof AppRestaurantRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/restaurant/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/restaurant/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/orders'
    | '/_app/profile'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/restaurant/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AppRestaurantRestaurantIdRoute: typeof AppRestaurantRestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/restaurant/$restaurantId': {
      id: '/_app/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof AppRestaurantRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AppRestaurantRestaurantIdRoute: AppRestaurantRestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
